# Introduction to Probability

<style>
hide {
  background-color: #d6d6d6;
  color: #d6d6d6;
}
hide:hover {
  background-color: white;
  color: black;
}
</style>

## Frequency Tables

The example from the previous section involves the "likelihood" of arresting the
correct person based on their hair color.  Here we begin the development of
"probability" which allows us to quantify the notion of likelihood.

Let's start by providing some additional context for our example: 
Suppose that the crime described takes place on an island of 1000 people. 
The number of these people with each hair color is given in the table below,
called a **frequency table.**

$$
\begin{array}{c|c}
 \mathrm{Color} & \mathrm{Count} \\ \hline
\mathrm{Brown} & 670  \\ 
\mathrm{Blond} & 200  \\ 
\mathrm{Red} & 110  \\ 
\mathrm{Green} & 20  \\ 
\end{array}\\
\mbox{Table 1: Hair Color Counts}
$$

```{r, warning=FALSE, echo=FALSE}
library(kableExtra)
table <- data.frame(Color = c("Brown", "Blond", "Red", "Green"), Count = c(670, 200, 110, 20))
table %>% kbl(caption = "Hair Color Counts") %>% kable_styling(full_width = FALSE)
```

A **probability** is a number between 0 and 1 that provides a measure of the 
likelihood that something occurs, 
with a larger number indicating greater likelihood. 

Suppose that we select a person from this population at random. To compute 
the probability that this person has brown hair,
we take the number with brown hair and divide by the number of people:

$$\mbox{P(Brown hair)} = \frac{670}{1000} = 0.67$$

We use "P(...)" to denote the probability of something. For instance in this case
$\mbox{P(Brown hair)}$ = "probability of brown hair".  

### Sample Questions

Sprinkled thought this book are Sample Questions, which also play the role
of examples. In the online version, the
solutions to these questions are hidden.  Before looking at the solution 
(by hovering), we recommend that you try to do them yourself!

**1.** What is the probability that a randomly selected person has blond hair?

**Answer:** <hide>$P(\text{Blond}) = \frac{200}{1000} = 0.20$.<hide>

**2.** What is the probability that a randomly selected person has red hair?

**Answer:** <hide>$P(\text{Red}) = \frac{110}{1000} = 0.11$.<hide>

---

## The Previous Example

The above examples are fine but they do not address the question from the 
previous section.
In Version 1, we have a brown-haired person on the CCTV and one of the
670 brown-haired people randomly arrested.
Thus the probability that the correct person is arrested is

$$\mbox{P(correct arrest)} = \frac{1}{670} = 0.00149$$

In Version 2 of the example we have a green-haired person on CCTV.
There are only 20 such people so this 
time the probability that the correct person is arrested is

$$\mbox{P(correct arrest)} = \frac{1}{20} = 0.05$$

We see that the probability of arresting the correct person if the suspect
has green hair is greater than the probability of a correct arrest if the
suspect has brown hair.  To measure how much greater, we divide
the two probabilities

$$\frac{0.05}{0.00149} = 33.5$$

Thus we see that a correct arrest in Version 2 is 33.5 times as likely as in Version 1.
However, even in Version 2 there is only a 0.05 probability that the police have
the correct person, so randomly arresting people based only on hair color is
not likely to produce the correct outcome in either case!

### Sample Questions

**1.** Suppose CCTV shows a red-haired person committed the robbery, and that
a random red-haired person is arrested.  What is the probability of a correct
arrest in this instance?

**Answer:** <hide>$P(\text{correct arrest}) = \frac{1}{110} = 0.00909$.<hide>

**2.** Determine the number of times greater the likelihood of a correct arrest
if the culprit has red hair vs having blond hair.

**Answer:** <hide>In the case of a blond-haired person, we have
$P(\text{correct arrest}) = \frac{1}{200} = 0.005$.  Therefore the ratio
of probabilities is
$\frac{0.00909}{0.005} = 1.81818$
so a correct arrest for a red-haired culprit is 1.81818 times as likely
as for a blond-haired culprit.
<hide>

---

## Exercises

1. $\text{Put exercises here}$
