# Conditional Probability

## Restricting the Pool

Let's continue with the blood type example from the preceding sections.  For
convenience the frequency table is included again below.

$$
\begin{array}{c|c|c}
       & + & - \\ \hline
\mathrm{A} & 360 & 60 \\ 
\mathrm{B} & 76 & 14 \\ 
\mathrm{AB} & 25 & 5 \\ 
\mathrm{O} & 390 & 70 \\ 
\end{array}\\
\mbox{Table 1: Frequencies by ABO and Rh groups}
$$

Now suppose that we focus only on those in our the population that have Rh group
$-$.  The frequency table for this subpopulation is just the $-$ column from 
Table 1.

$$
\begin{array}{c|c}
       & - \\ \hline
\mathrm{A} &  60 \\ 
\mathrm{B} &  14 \\ 
\mathrm{AB} &  5 \\ 
\mathrm{O} &  70 \\ 
\end{array}\\
\mbox{Table 2: Frequencies by ABO groups among those in Rh} - \mbox{group}
$$

There is no reason why we cannot compute probabilities based on this one column
of data, provided we specify that is what we are doing.  

## Conditional Probability

Let's compute a probability based on the data in Table 2.  For instance, suppose
that a person from the Rh $-$ group is selected at random.
The probability that this person has ABO group A is an 
example of a **conditional probability**.  There are a total of 149 people in the
Rh group $-$, with 60 of those having ABO group A.
Therefore the probability that an Rh group $-$ person selected at random is 
ABO group A is

$$
\mbox{P(ABO group A | Rh group }-) = \frac{60}{149} = 0.403
$$

The vertical bar in the notation means "given that" 
so that $\mbox{P(ABO group A | Rh group }-)$ is read as 

$$
\mbox{The probability of ABO group A, given the person is Rh group }-.
$$
Note that we might abbreviate the notation to
$\mbox{P(A | }-)$ for compactness in cases where the brevity is not confusing.
Conditional probabilities arise all the time when evaluating forensic evidence.
(In fact almost all probabilities encountered are conditional.)

For another example, suppose that we want to determine P($+$ | AB), 
the probability that someone is Rh $+$ given that they are ABO group AB.
Referring back to Table 1, we see that there are $25 + 5 = 30$ people 
who are ABO group AB, and among those there are 25 who are also Rh $+$.
Thus we have

$$
\mbox{P(}+\mbox{ | AB)} = \frac{25}{30} = 0.833
$$

In a similar manner, we can compute

$$
\mbox{P(}+\mbox{ | O)} = \frac{390}{460} = 0.833
$$

The probability the person is female, given Type B blood:

$$
\mbox{P(Female | Type B)} = \frac{37}{100} = 0.37
$$

The probability the person is male, given Type A blood:

$$
\mbox{P(Male | Type A)} = \frac{235}{410} = 0.573
$$
   
### Sample Questions

<style>
hide {
  background-color: #d6d6d6;
  color: #d6d6d6;
}
hide:hover {
  background-color: white;
  color: black;
}
</style>

**1.** What is the probability of blood type AB or B given the person selected is female?

**Answer:** <hide>$P(\text{AB or B | Female}) = (16 + 37) / 430 = 0.123$<hide>
