# Probability Rules

## Multiplication Rule

In this section we again use the blood type data in Table 1 below.

$$
\begin{array}{c|c|c}
       & + & - \\ \hline
\mathrm{A} & 360 & 60 \\ 
\mathrm{B} & 76 & 14 \\ 
\mathrm{AB} & 25 & 5 \\ 
\mathrm{O} & 390 & 70 \\ 
\end{array}\\
\mbox{Table 1: Frequencies by ABO and Rh groups}
$$

In the previous section we computed the conditional probability

$$
\mbox{P(A | }-) = \frac{60}{149} = 0.403
$$

based on the data in Table 1.  
The numerator 60 came from the number of Rh $-$ people who are also ABO group A, 
and the denominator 149 is the total number of Rh $-$ people. 
If we divide the numerator and denominator by 1000, then the quotient is not changed
so that we have

$$
\mbox{P(A | }-) = \frac{60/1000}{149/1000} 
= \frac{0.060}{0.149} = \frac{\mbox{P(A and }-)}{\mbox{P(}-)}
$$

This illustrates a general property of probability: If X and Y represent possible 
outcomes from a random event, then the probability of X given Y is

$$
\mbox{P(X | Y)} = \frac{\mbox{P(X and Y)}}{\mbox{P(Y)}}
$$

Multiplying on both sides of the above equation by P(Y) gives

$$
\mbox{P(X and Y)} = \mbox{P(X | Y)}\mbox{P(Y)}  
$$

This is called the **multiplication rule**, and it allows us to move back and forth
between joint probabilities and conditional probabilities.  

Let's try this out, using Table 2 (which we saw previously).  

$$
\begin{array}{c|c|c}
       & + & - \\ \hline
\mathrm{A} & 0.360 & 0.060 \\ 
\mathrm{B} & 0.076 & 0.014 \\ 
\mathrm{AB} & 0.025 & 0.005 \\ 
\mathrm{O} & 0.390 & 0.070 \\ 
\end{array}\\
\mbox{Table 2: Probabilities by ABO and Rh groups}
$$



---

## Exercises

1. $\text{Put exercises here}$
