# Graphing Distributions: Histograms

 <font size="2"> Note: Portions below modeled after content from
 *Online Statistics Education: A Multimedia Course of Study* 
 (http://onlinestatbook.com/) Project Leader: David M. Lane, Rice University </font>
 
## Introduction

The "distribution" of a set of data consists of the set of possible data values and the
frequency that the values occur.
A **histogram** is a graphical method for displaying the shape of a distribution. 
It is particularly useful when there are a large number of data values, when
it is not practical to list all values. 

We begin with an example consisting of the weights of 371 bags containing a
substance suspected of being narcotics.  The weights of the bags range from
215 to 270 grams.  We begin by creating a frequency table of groupings of weights
as shown in Table 1.

$$
\begin{array}{|c|c|r|} \hline
\mathrm{Interval} & \mathrm{Interval} & \mathrm{Class}\hspace{.175in}\\
\text{Lower Limit} & \text{Upper Limit} & \mathrm{Frequency} \\ \hline
215 & 220 & 4\hspace{.3in} \\  \hline
220 & 225  & 8\hspace{.3in} \\  \hline
225 & 230 & 31\hspace{.3in} \\  \hline
230 & 235 & 74\hspace{.3in} \\  \hline
235 & 240 & 88\hspace{.3in} \\  \hline
240 & 245 & 75\hspace{.3in} \\  \hline
245 & 250 & 57\hspace{.3in} \\  \hline
250 & 255 & 25\hspace{.3in} \\  \hline
255 & 260 & 8\hspace{.3in} \\  \hline
260 & 265 & 1\hspace{.3in} \\  \hline
\end{array}\\
\mbox{Table 1: Grouped Frequency Distribution of Weights}
$$

To create this table, the range of weights was broken into intervals, called class intervals. 
The first interval is from 215 to 220, the second from 220 to 225, etc. Next, the number of weights
falling into each interval was counted to obtain the class frequencies. There are four weights  
in the first interval, eight in the second, etc.

Class intervals of width 5 provide enough detail about the distribution to be revealing without 
making the graph too "choppy." How one goes about choosing the widths (called "bin widths") of 
class intervals is discussed later in this section. 

In a histogram, the class frequencies are represented by bars. The height of each bar corresponds 
to its class frequency. A histogram of the weight data is shown in Figure \@ref(fig:histogram).

```{r histogram, fig.cap="Histogram of weights", echo=FALSE}
set.seed(4)
data01 = rnorm(371, mean=239, sd=8)
for (i in 1:371) {
  if (data01[i] > 239) {
    data01[i] = 239 + 1.1*(data01[i]-239)
  }
}
data01 <- data.frame(Weights = data01)
ggplot(data01, aes(Weights)) + 
  geom_histogram(breaks = seq(215, 265, by=5),
                 fill = "steelblue",
                 color = "black") + 
  labs(x="Weights", y="Frequency")
```

We can see from the histogram that most of the weights are between 230 and 250 grams,
with fewer weights in the extremes.  We can also see that the distribution is not 
quite symmetric, the weights extend to the right farther than to the left.  This
distribution is therefore said to be *skewed*.

Although we cannot see the exact data values, they are measured to two decimal 
places so it is not likely that we get many "fence-sitters" -- that is, values
that land right on the border.

In our example, the observations are whole numbers. Histograms can also be used when the scores are measured on a more continuous scale such as the length of time (in milliseconds) required to perform a task. In this case, there is no need to worry about fence-sitters since they are improbable. (It would be quite a coincidence for a task to require exactly 7 seconds, measured to the nearest thousandth of a second.) We are therefore free to choose whole numbers as boundaries for our class intervals, for example, 4000, 5000, etc. The class frequency is then the number of observations that are greater than or equal to the lower bound, and strictly less than the upper bound. For example, one interval might hold times from 4000 to 4999 milliseconds. Using whole numbers as boundaries avoids a cluttered appearance, and is the practice of many computer programs that create histograms. Note also that some computer programs label the middle of each interval rather than the end points.

Histograms can be based on relative frequencies instead of actual frequencies. Histograms based on relative frequencies show the proportion of scores in each interval rather than the number of scores. In this case, the Y-axis runs from 0 to 1 (or somewhere in between if there are no extreme proportions). You can change a histogram based on frequencies to one based on relative frequencies by (a) dividing each class frequency by the total number of observations, and then (b) plotting the quotients on the Y-axis (labeled as proportion).

There is more to be said about the widths of the class intervals, sometimes called bin widths. Your choice of bin width determines the number of class intervals. This decision, along with the choice of starting point for the first interval, affects the shape of the histogram. There are some "rules of thumb" that can help you choose an appropriate width. (But keep in mind that none of the rules is perfect.) Sturges' rule is to set the number of intervals as close as possible to 1 + Log2(N), where Log2(N) is the base 2 log of the number of observations. The formula can also be written as 1 + 3.3 Log10(N), where Log10(N) is the log base 10 of the number of observations. According to Sturges' rule, 1000 observations would be graphed with 11 class intervals since 10 is the closest integer to Log2(1000). We prefer the Rice rule, which is to set the number of intervals to twice the cube root of the number of observations. In the case of 1000 observations, the Rice rule yields 20 intervals instead of the 11 recommended by Sturges' rule. For the psychology test example used above, Sturges' rule recommends 10 intervals while the Rice rule recommends 17. In the end, we compromised and chose 13 intervals for Figure 1 to create a histogram that seemed clearest. The best advice is to experiment with different choices of width, and to choose a histogram according to how well it communicates the shape of the distribution.

---

## Exercises

1. $\text{Put exercises here}$
