--- 
title: "Forensic Science and Statistics: Version 1.0.1"
author: "Jeff Holt and Joseph Swetonic"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    toc_depth: 1
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the first pass at the forensic science and statistics book. The output format for this example is bookdown::gitbook."
---

# Welcome

**This is a draft version of a work in progress. It is NOT intended for circulation.**

This book introduces statistical methods that are of use in forensic science. 
In some cases the methods are currently used.
In others the methods are described but not generally in use, 
although we hope that eventually they will be!  

We assume that the reader has a basic understanding of mathematics, but no prior 
knowledge of statistics is required.
We will provide a modest description of forensic methods, but as many of these are 
highly nuanced we do not attempt to 
provide a deep treatment of forensic methods here. However, when possible we will 
try to provide references to more information.

Portions of this book that borrow from the treatment of statistics 
given in the online materials:

> Online Statistics Education: A Multimedia Course of Study (http://onlinestatbook.com/) 
> Project Leader: David M. Lane, Rice University

This site provides a comprehensive introduction to statistics and is an excellent 
resource for additional information. 
We deeply appreciate their willingness to allow the use of their work.

## An Introductory Example

Consider the following scenario:
Suppose there is a late-night break-in at a closed convenience store.
No one is present to see the perpetrator, but there is low-quality CCTV footage. 
Unfortunately, the *only* thing that can be discerned from the video is the 
color of the perpetrator's hair.

Now consider two possible versions of what comes next:

**Version 1**: The video shows that the perpetrator has *brown* hair. 
The day after the robbery, police see a person with brown hair walking down the street. 
The person is arrested on suspicion of committing the break-in.

**Version 2**: The video shows that the perpetrator has *green* hair.  The 
day after the robbery, police see a person with green hair walking down the street. 
The person is arrested on suspicion of committing the break-in.

For the sake of this simplified example, 
in both versions we assume that the color of the hair is the **only** reason the 
police suspect the person who is arrested.

**Question**: In which version do you think it is more likely that the police have 
arrested the person who committed the break-in?

Answering the question requires considering the likelihood that the police have 
the correct person in both versions and deciding which is greater.
In most communities people with brown hair outnumber people with green hair,
so let's assume that is the case here. Intuitively,
it seems reasonable to expect that the likelihood of a correct arrest in Version 2 is greater 
than that in Version 1: 
Brown-haired people are relatively common, so in Version 1 the likelihood of 
arresting the correct brown-haired person is probably low. 
On the other hand, green-haired people are relatively rare, so in Version 2 
the likelihood of arresting the correct person is higher than in Version 1.

While the above discussion might be interesting, the word "likelihood" is 
imprecise.  Our goal in this book is to develop mathematical tools that 
allows us to quantify the notion of likelihood. 
This will allow us 
to specify (for instance) how much more likely a correct arrest is in
Version 1 than in Version 2.  We take this up in the next chapter.

## Exercises

1. $\text{Put exercises here}$



